export About from './About/About'
export Account from './Account/Account'
export App from './App/App'
export Home from './Home/Home'
export Login from './Login/Login'
export Profile from './Profile/Profile'
export Registration from './Registration/Registration'