export About from './About/About'
export Account from './Account/Account'
export App from './App/App'
export EditProfile from './EditProfile/EditProfile'
export Home from './Home/Home'
export Login from './Login/Login'
export Profile from './Profile/Profile'
export Register from './Register/Register'